### ISSUE TITLE
More intuitive renaming of color profiles

### ISSUE THREAD

**Issue by ghost** [fsobolev/cavalier#29]
It's hard to recreate a color profile under a different name. There should be an option to rename them.

**Comment by fsobolev** [comment]
> It's hard to recreate a color profile under a different name.

It's not that hard. When you create a new profile, it will be a copy of an active profile, not the default one. This is intended, I didn't want to clutter the interface with renaming functionality. So if you want to rename profile you can:
1. Select a profile you want to rename
2. Create a new profile with desired name
3. Remove original profile

But I agree that it's not intuitive. Maybe instead of renaming functionality it would be good to add "?" button that opens a popover describing how to rename profile and maybe some other hints?

**Comment by ghost** [comment]
>  Select a profile you want to rename
    Create a new profile with desired name
    Remove original profile

Ah, I see.

> Maybe instead of renaming functionality it would be good to add "?" button that opens a popover describing how to rename profile and maybe some other hints?

I think that wouldn't be worth the extra button. Instead, there should be a little text underneath the box where you enter the name of the new profile, something along the lines of "The new profile will be a copy of the active profile."

**Comment by fsobolev** [comment]
> Instead, there should be a little text underneath the box where you enter the name of the new profile, something along the lines of "The new profile will be a copy of the active profile."

Great idea! There's already a label to show error when a name is already in use, it's empty by default but it can be used to show this hint.
