### ISSUE TITLE
Reverse the default order of bars

### ISSUE THREAD

**Issue by ghost** [fsobolev/cavalier#34]
Right now, in stereo channel, the middle bars are the bars, the outer bars are the highs.
In mono channel, the bars to the left are bass, the ones to the right are highs. 

It should be the other way around by default, especially considering the recently added Spine mode.

**Comment by fsobolev** [comment]
The problem is, with stereo channels bass bars in the middle are the default behavior of CAVA... And I want to keep the app predictable for those who start using it after CAVA and expect some functionality to be the same.
But if we don't look at CAVA, I agree that having bass bars on sides with stereo channels is more appropriate default. So I suggest to only change the default state of reverse order option: true instead of false. This way we'll have better default but CAVA "compatibility" will not be broken.
The question is, should we change the order for vertical Spine mode or not. I think we shouldn't, because if reversed order will be default, in vertical Spine bass bars will be on bottom by default, just like I wanted.

**Comment by fsobolev** [comment]
I changed the default value in https://github.com/fsobolev/cavalier/commit/254f976c47db297d83dcdd836c2e6b34574473ee. If you agree that it's enough, you can close the issue

**Comment by ghost** [comment]
> I changed the default value in [254f976](https://github.com/fsobolev/cavalier/commit/254f976c47db297d83dcdd836c2e6b34574473ee). If you agree that it's enough, you can close the issue

That fixes it, then.
