### ISSUE TITLE
Feature Request - Attach to specific application

### ISSUE THREAD

**Issue by forever-and-a-day** [fsobolev/cavalier#43]
Would be nice to be able to attach cavalier to a music player so something like a voice call or video doesn't affect it.

**Comment by fsobolev** [comment]
Unfortunately [CAVA](https://github.com/karlstav/cava) doesn't support this. It allows to set pulseaudio source (in pulseaudio context source is not an application, but something like a device, it can be purely virtual), and I want in the future to make CAVA config used by Cavalier not harcoded to let users modify it, so it will be possible, for example, to run Cavalier with MPD.
But anyway, it's currently possible to achieve what you want. Connections between applications and devices can be changed both for pulseaudio and pipewire. I can't really give you any instructions if your system still uses pulseaudio, but for pipewire the easiest way is to use [Helvum](https://flathub.org/apps/details/org.pipewire.Helvum).

![image](https://user-images.githubusercontent.com/117388856/216877416-92955f34-5f3b-499c-9ff1-d9f07f75ab47.png)

This is a simple example. Amberol and Chromium both play sound, but I changed connections so cava is listening only to Amberol instead of my output device.

I hope it helps.
