### ISSUE TITLE
Window buttons/header bar

### ISSUE THREAD

**Issue by ghost** [fsobolev/cavalier#5]
It would be nice to have the Close/Maximize buttons in a header bar at the top of the window. That makes it much easier to perform those actions. The visualization looks nicer without the header bar though, so you could do it the way [Apostrophe](https://gitlab.gnome.org/World/apostrophe/) does and make the header bar disappear when the cursor is inactive.

**Comment by fsobolev** [comment]
It's not like closing or maximizing Cavalier window is a task that a user would do often, so I don't see a reason to make window buttons accessible as fast as possible. Especially since it's still pretty easy and fast (2 clicks instead of 1 to close the window, and maximizing can be done in different ways within a second or two). And showing window buttons on hover can be distracting if it's done accidentally, so I don't think it's a good solution.
What needs to be fixed - and I noticed it just now thanks to your suggestion - is that the app remembers its window size in unmaximized state, but it doesn't remember if it was maximized or not. So if the need to maximize the window manually every time the app starts is what bothers you, this will be fixed. 🙂

**Edit**: I think it might be a not bad idea to hide window buttons and show them not on hover, but when the window is focused. I will try to implement it.
